// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.27.1
// source: segment/v1/segment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSegmentServiceAddUsersToStaticSegment = "/api.segment.v1.SegmentService/AddUsersToStaticSegment"
const OperationSegmentServiceCreateSegment = "/api.segment.v1.SegmentService/CreateSegment"
const OperationSegmentServiceDeleteSegment = "/api.segment.v1.SegmentService/DeleteSegment"
const OperationSegmentServiceEvaluateSegment = "/api.segment.v1.SegmentService/EvaluateSegment"
const OperationSegmentServiceGetDistinctValues = "/api.segment.v1.SegmentService/GetDistinctValues"
const OperationSegmentServiceGetSegment = "/api.segment.v1.SegmentService/GetSegment"
const OperationSegmentServiceGetSegmentUserCount = "/api.segment.v1.SegmentService/GetSegmentUserCount"
const OperationSegmentServiceListSegments = "/api.segment.v1.SegmentService/ListSegments"
const OperationSegmentServicePreviewSegment = "/api.segment.v1.SegmentService/PreviewSegment"
const OperationSegmentServiceRemoveUsersFromStaticSegment = "/api.segment.v1.SegmentService/RemoveUsersFromStaticSegment"
const OperationSegmentServiceUpdateSegment = "/api.segment.v1.SegmentService/UpdateSegment"
const OperationSegmentServiceUploadStaticSegment = "/api.segment.v1.SegmentService/UploadStaticSegment"

type SegmentServiceHTTPServer interface {
	// AddUsersToStaticSegment AddUsersToStaticSegment adds users to an existing static segment
	AddUsersToStaticSegment(context.Context, *AddUsersToStaticSegmentRequest) (*AddUsersToStaticSegmentResponse, error)
	// CreateSegment CreateSegment creates a new segment definition
	CreateSegment(context.Context, *CreateSegmentRequest) (*CreateSegmentResponse, error)
	// DeleteSegment DeleteSegment deletes a segment
	DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error)
	// EvaluateSegment EvaluateSegment evaluates a segment and returns user IDs
	EvaluateSegment(context.Context, *EvaluateSegmentRequest) (*EvaluateSegmentResponse, error)
	// GetDistinctValues GetDistinctValues returns distinct values for a profile field
	GetDistinctValues(context.Context, *GetDistinctValuesRequest) (*GetDistinctValuesResponse, error)
	// GetSegment GetSegment retrieves a segment by ID
	GetSegment(context.Context, *GetSegmentRequest) (*GetSegmentResponse, error)
	// GetSegmentUserCount GetSegmentUserCount returns the count of users in a segment
	GetSegmentUserCount(context.Context, *GetSegmentUserCountRequest) (*GetSegmentUserCountResponse, error)
	// ListSegments ListSegments lists all segments with pagination
	ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error)
	// PreviewSegment PreviewSegment previews segment results without saving
	PreviewSegment(context.Context, *PreviewSegmentRequest) (*PreviewSegmentResponse, error)
	// RemoveUsersFromStaticSegment RemoveUsersFromStaticSegment removes users from a static segment
	RemoveUsersFromStaticSegment(context.Context, *RemoveUsersFromStaticSegmentRequest) (*RemoveUsersFromStaticSegmentResponse, error)
	// UpdateSegment UpdateSegment updates an existing segment
	UpdateSegment(context.Context, *UpdateSegmentRequest) (*UpdateSegmentResponse, error)
	// UploadStaticSegment UploadStaticSegment creates a static segment from uploaded user IDs
	UploadStaticSegment(context.Context, *UploadStaticSegmentRequest) (*UploadStaticSegmentResponse, error)
}

func RegisterSegmentServiceHTTPServer(s *http.Server, srv SegmentServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/segments", _SegmentService_CreateSegment0_HTTP_Handler(srv))
	r.PUT("/v1/segments/{id}", _SegmentService_UpdateSegment0_HTTP_Handler(srv))
	r.GET("/v1/segments/{id}", _SegmentService_GetSegment0_HTTP_Handler(srv))
	r.GET("/v1/segments", _SegmentService_ListSegments0_HTTP_Handler(srv))
	r.DELETE("/v1/segments/{id}", _SegmentService_DeleteSegment0_HTTP_Handler(srv))
	r.POST("/v1/segments/{id}/evaluate", _SegmentService_EvaluateSegment0_HTTP_Handler(srv))
	r.POST("/v1/segments/preview", _SegmentService_PreviewSegment0_HTTP_Handler(srv))
	r.GET("/v1/segments/{id}/count", _SegmentService_GetSegmentUserCount0_HTTP_Handler(srv))
	r.POST("/v1/segments/upload", _SegmentService_UploadStaticSegment0_HTTP_Handler(srv))
	r.POST("/v1/segments/{id}/users", _SegmentService_AddUsersToStaticSegment0_HTTP_Handler(srv))
	r.DELETE("/v1/segments/{id}/users", _SegmentService_RemoveUsersFromStaticSegment0_HTTP_Handler(srv))
	r.GET("/v1/segments/distinct-values/{field}", _SegmentService_GetDistinctValues0_HTTP_Handler(srv))
}

func _SegmentService_CreateSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSegmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceCreateSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSegment(ctx, req.(*CreateSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_UpdateSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSegmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceUpdateSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSegment(ctx, req.(*UpdateSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_GetSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSegmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceGetSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSegment(ctx, req.(*GetSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_ListSegments0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSegmentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceListSegments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSegments(ctx, req.(*ListSegmentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSegmentsResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_DeleteSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSegmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceDeleteSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSegment(ctx, req.(*DeleteSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_EvaluateSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EvaluateSegmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceEvaluateSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EvaluateSegment(ctx, req.(*EvaluateSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EvaluateSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_PreviewSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreviewSegmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServicePreviewSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewSegment(ctx, req.(*PreviewSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_GetSegmentUserCount0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSegmentUserCountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceGetSegmentUserCount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSegmentUserCount(ctx, req.(*GetSegmentUserCountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSegmentUserCountResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_UploadStaticSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadStaticSegmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceUploadStaticSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadStaticSegment(ctx, req.(*UploadStaticSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadStaticSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_AddUsersToStaticSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddUsersToStaticSegmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceAddUsersToStaticSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddUsersToStaticSegment(ctx, req.(*AddUsersToStaticSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddUsersToStaticSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_RemoveUsersFromStaticSegment0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveUsersFromStaticSegmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceRemoveUsersFromStaticSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveUsersFromStaticSegment(ctx, req.(*RemoveUsersFromStaticSegmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveUsersFromStaticSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SegmentService_GetDistinctValues0_HTTP_Handler(srv SegmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDistinctValuesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSegmentServiceGetDistinctValues)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDistinctValues(ctx, req.(*GetDistinctValuesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDistinctValuesResponse)
		return ctx.Result(200, reply)
	}
}

type SegmentServiceHTTPClient interface {
	// AddUsersToStaticSegment AddUsersToStaticSegment adds users to an existing static segment
	AddUsersToStaticSegment(ctx context.Context, req *AddUsersToStaticSegmentRequest, opts ...http.CallOption) (rsp *AddUsersToStaticSegmentResponse, err error)
	// CreateSegment CreateSegment creates a new segment definition
	CreateSegment(ctx context.Context, req *CreateSegmentRequest, opts ...http.CallOption) (rsp *CreateSegmentResponse, err error)
	// DeleteSegment DeleteSegment deletes a segment
	DeleteSegment(ctx context.Context, req *DeleteSegmentRequest, opts ...http.CallOption) (rsp *DeleteSegmentResponse, err error)
	// EvaluateSegment EvaluateSegment evaluates a segment and returns user IDs
	EvaluateSegment(ctx context.Context, req *EvaluateSegmentRequest, opts ...http.CallOption) (rsp *EvaluateSegmentResponse, err error)
	// GetDistinctValues GetDistinctValues returns distinct values for a profile field
	GetDistinctValues(ctx context.Context, req *GetDistinctValuesRequest, opts ...http.CallOption) (rsp *GetDistinctValuesResponse, err error)
	// GetSegment GetSegment retrieves a segment by ID
	GetSegment(ctx context.Context, req *GetSegmentRequest, opts ...http.CallOption) (rsp *GetSegmentResponse, err error)
	// GetSegmentUserCount GetSegmentUserCount returns the count of users in a segment
	GetSegmentUserCount(ctx context.Context, req *GetSegmentUserCountRequest, opts ...http.CallOption) (rsp *GetSegmentUserCountResponse, err error)
	// ListSegments ListSegments lists all segments with pagination
	ListSegments(ctx context.Context, req *ListSegmentsRequest, opts ...http.CallOption) (rsp *ListSegmentsResponse, err error)
	// PreviewSegment PreviewSegment previews segment results without saving
	PreviewSegment(ctx context.Context, req *PreviewSegmentRequest, opts ...http.CallOption) (rsp *PreviewSegmentResponse, err error)
	// RemoveUsersFromStaticSegment RemoveUsersFromStaticSegment removes users from a static segment
	RemoveUsersFromStaticSegment(ctx context.Context, req *RemoveUsersFromStaticSegmentRequest, opts ...http.CallOption) (rsp *RemoveUsersFromStaticSegmentResponse, err error)
	// UpdateSegment UpdateSegment updates an existing segment
	UpdateSegment(ctx context.Context, req *UpdateSegmentRequest, opts ...http.CallOption) (rsp *UpdateSegmentResponse, err error)
	// UploadStaticSegment UploadStaticSegment creates a static segment from uploaded user IDs
	UploadStaticSegment(ctx context.Context, req *UploadStaticSegmentRequest, opts ...http.CallOption) (rsp *UploadStaticSegmentResponse, err error)
}

type SegmentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSegmentServiceHTTPClient(client *http.Client) SegmentServiceHTTPClient {
	return &SegmentServiceHTTPClientImpl{client}
}

// AddUsersToStaticSegment AddUsersToStaticSegment adds users to an existing static segment
func (c *SegmentServiceHTTPClientImpl) AddUsersToStaticSegment(ctx context.Context, in *AddUsersToStaticSegmentRequest, opts ...http.CallOption) (*AddUsersToStaticSegmentResponse, error) {
	var out AddUsersToStaticSegmentResponse
	pattern := "/v1/segments/{id}/users"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSegmentServiceAddUsersToStaticSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSegment CreateSegment creates a new segment definition
func (c *SegmentServiceHTTPClientImpl) CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...http.CallOption) (*CreateSegmentResponse, error) {
	var out CreateSegmentResponse
	pattern := "/v1/segments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSegmentServiceCreateSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSegment DeleteSegment deletes a segment
func (c *SegmentServiceHTTPClientImpl) DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...http.CallOption) (*DeleteSegmentResponse, error) {
	var out DeleteSegmentResponse
	pattern := "/v1/segments/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSegmentServiceDeleteSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// EvaluateSegment EvaluateSegment evaluates a segment and returns user IDs
func (c *SegmentServiceHTTPClientImpl) EvaluateSegment(ctx context.Context, in *EvaluateSegmentRequest, opts ...http.CallOption) (*EvaluateSegmentResponse, error) {
	var out EvaluateSegmentResponse
	pattern := "/v1/segments/{id}/evaluate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSegmentServiceEvaluateSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDistinctValues GetDistinctValues returns distinct values for a profile field
func (c *SegmentServiceHTTPClientImpl) GetDistinctValues(ctx context.Context, in *GetDistinctValuesRequest, opts ...http.CallOption) (*GetDistinctValuesResponse, error) {
	var out GetDistinctValuesResponse
	pattern := "/v1/segments/distinct-values/{field}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSegmentServiceGetDistinctValues))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSegment GetSegment retrieves a segment by ID
func (c *SegmentServiceHTTPClientImpl) GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...http.CallOption) (*GetSegmentResponse, error) {
	var out GetSegmentResponse
	pattern := "/v1/segments/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSegmentServiceGetSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSegmentUserCount GetSegmentUserCount returns the count of users in a segment
func (c *SegmentServiceHTTPClientImpl) GetSegmentUserCount(ctx context.Context, in *GetSegmentUserCountRequest, opts ...http.CallOption) (*GetSegmentUserCountResponse, error) {
	var out GetSegmentUserCountResponse
	pattern := "/v1/segments/{id}/count"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSegmentServiceGetSegmentUserCount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSegments ListSegments lists all segments with pagination
func (c *SegmentServiceHTTPClientImpl) ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...http.CallOption) (*ListSegmentsResponse, error) {
	var out ListSegmentsResponse
	pattern := "/v1/segments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSegmentServiceListSegments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PreviewSegment PreviewSegment previews segment results without saving
func (c *SegmentServiceHTTPClientImpl) PreviewSegment(ctx context.Context, in *PreviewSegmentRequest, opts ...http.CallOption) (*PreviewSegmentResponse, error) {
	var out PreviewSegmentResponse
	pattern := "/v1/segments/preview"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSegmentServicePreviewSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveUsersFromStaticSegment RemoveUsersFromStaticSegment removes users from a static segment
func (c *SegmentServiceHTTPClientImpl) RemoveUsersFromStaticSegment(ctx context.Context, in *RemoveUsersFromStaticSegmentRequest, opts ...http.CallOption) (*RemoveUsersFromStaticSegmentResponse, error) {
	var out RemoveUsersFromStaticSegmentResponse
	pattern := "/v1/segments/{id}/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSegmentServiceRemoveUsersFromStaticSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSegment UpdateSegment updates an existing segment
func (c *SegmentServiceHTTPClientImpl) UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...http.CallOption) (*UpdateSegmentResponse, error) {
	var out UpdateSegmentResponse
	pattern := "/v1/segments/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSegmentServiceUpdateSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadStaticSegment UploadStaticSegment creates a static segment from uploaded user IDs
func (c *SegmentServiceHTTPClientImpl) UploadStaticSegment(ctx context.Context, in *UploadStaticSegmentRequest, opts ...http.CallOption) (*UploadStaticSegmentResponse, error) {
	var out UploadStaticSegmentResponse
	pattern := "/v1/segments/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSegmentServiceUploadStaticSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
