// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.1
// source: segment/v1/segment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SegmentService_CreateSegment_FullMethodName                = "/api.segment.v1.SegmentService/CreateSegment"
	SegmentService_UpdateSegment_FullMethodName                = "/api.segment.v1.SegmentService/UpdateSegment"
	SegmentService_GetSegment_FullMethodName                   = "/api.segment.v1.SegmentService/GetSegment"
	SegmentService_ListSegments_FullMethodName                 = "/api.segment.v1.SegmentService/ListSegments"
	SegmentService_DeleteSegment_FullMethodName                = "/api.segment.v1.SegmentService/DeleteSegment"
	SegmentService_EvaluateSegment_FullMethodName              = "/api.segment.v1.SegmentService/EvaluateSegment"
	SegmentService_PreviewSegment_FullMethodName               = "/api.segment.v1.SegmentService/PreviewSegment"
	SegmentService_GetSegmentUserCount_FullMethodName          = "/api.segment.v1.SegmentService/GetSegmentUserCount"
	SegmentService_UploadStaticSegment_FullMethodName          = "/api.segment.v1.SegmentService/UploadStaticSegment"
	SegmentService_AddUsersToStaticSegment_FullMethodName      = "/api.segment.v1.SegmentService/AddUsersToStaticSegment"
	SegmentService_RemoveUsersFromStaticSegment_FullMethodName = "/api.segment.v1.SegmentService/RemoveUsersFromStaticSegment"
)

// SegmentServiceClient is the client API for SegmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SegmentServiceClient interface {
	// CreateSegment creates a new segment definition
	CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...grpc.CallOption) (*CreateSegmentResponse, error)
	// UpdateSegment updates an existing segment
	UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...grpc.CallOption) (*UpdateSegmentResponse, error)
	// GetSegment retrieves a segment by ID
	GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...grpc.CallOption) (*GetSegmentResponse, error)
	// ListSegments lists all segments with pagination
	ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error)
	// DeleteSegment deletes a segment
	DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...grpc.CallOption) (*DeleteSegmentResponse, error)
	// EvaluateSegment evaluates a segment and returns user IDs
	EvaluateSegment(ctx context.Context, in *EvaluateSegmentRequest, opts ...grpc.CallOption) (*EvaluateSegmentResponse, error)
	// PreviewSegment previews segment results without saving
	PreviewSegment(ctx context.Context, in *PreviewSegmentRequest, opts ...grpc.CallOption) (*PreviewSegmentResponse, error)
	// GetSegmentUserCount returns the count of users in a segment
	GetSegmentUserCount(ctx context.Context, in *GetSegmentUserCountRequest, opts ...grpc.CallOption) (*GetSegmentUserCountResponse, error)
	// UploadStaticSegment creates a static segment from uploaded user IDs
	UploadStaticSegment(ctx context.Context, in *UploadStaticSegmentRequest, opts ...grpc.CallOption) (*UploadStaticSegmentResponse, error)
	// AddUsersToStaticSegment adds users to an existing static segment
	AddUsersToStaticSegment(ctx context.Context, in *AddUsersToStaticSegmentRequest, opts ...grpc.CallOption) (*AddUsersToStaticSegmentResponse, error)
	// RemoveUsersFromStaticSegment removes users from a static segment
	RemoveUsersFromStaticSegment(ctx context.Context, in *RemoveUsersFromStaticSegmentRequest, opts ...grpc.CallOption) (*RemoveUsersFromStaticSegmentResponse, error)
}

type segmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmentServiceClient(cc grpc.ClientConnInterface) SegmentServiceClient {
	return &segmentServiceClient{cc}
}

func (c *segmentServiceClient) CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...grpc.CallOption) (*CreateSegmentResponse, error) {
	out := new(CreateSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_CreateSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...grpc.CallOption) (*UpdateSegmentResponse, error) {
	out := new(UpdateSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_UpdateSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...grpc.CallOption) (*GetSegmentResponse, error) {
	out := new(GetSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_GetSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error) {
	out := new(ListSegmentsResponse)
	err := c.cc.Invoke(ctx, SegmentService_ListSegments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...grpc.CallOption) (*DeleteSegmentResponse, error) {
	out := new(DeleteSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_DeleteSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) EvaluateSegment(ctx context.Context, in *EvaluateSegmentRequest, opts ...grpc.CallOption) (*EvaluateSegmentResponse, error) {
	out := new(EvaluateSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_EvaluateSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) PreviewSegment(ctx context.Context, in *PreviewSegmentRequest, opts ...grpc.CallOption) (*PreviewSegmentResponse, error) {
	out := new(PreviewSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_PreviewSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) GetSegmentUserCount(ctx context.Context, in *GetSegmentUserCountRequest, opts ...grpc.CallOption) (*GetSegmentUserCountResponse, error) {
	out := new(GetSegmentUserCountResponse)
	err := c.cc.Invoke(ctx, SegmentService_GetSegmentUserCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) UploadStaticSegment(ctx context.Context, in *UploadStaticSegmentRequest, opts ...grpc.CallOption) (*UploadStaticSegmentResponse, error) {
	out := new(UploadStaticSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_UploadStaticSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) AddUsersToStaticSegment(ctx context.Context, in *AddUsersToStaticSegmentRequest, opts ...grpc.CallOption) (*AddUsersToStaticSegmentResponse, error) {
	out := new(AddUsersToStaticSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_AddUsersToStaticSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) RemoveUsersFromStaticSegment(ctx context.Context, in *RemoveUsersFromStaticSegmentRequest, opts ...grpc.CallOption) (*RemoveUsersFromStaticSegmentResponse, error) {
	out := new(RemoveUsersFromStaticSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_RemoveUsersFromStaticSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SegmentServiceServer is the server API for SegmentService service.
// All implementations must embed UnimplementedSegmentServiceServer
// for forward compatibility
type SegmentServiceServer interface {
	// CreateSegment creates a new segment definition
	CreateSegment(context.Context, *CreateSegmentRequest) (*CreateSegmentResponse, error)
	// UpdateSegment updates an existing segment
	UpdateSegment(context.Context, *UpdateSegmentRequest) (*UpdateSegmentResponse, error)
	// GetSegment retrieves a segment by ID
	GetSegment(context.Context, *GetSegmentRequest) (*GetSegmentResponse, error)
	// ListSegments lists all segments with pagination
	ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error)
	// DeleteSegment deletes a segment
	DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error)
	// EvaluateSegment evaluates a segment and returns user IDs
	EvaluateSegment(context.Context, *EvaluateSegmentRequest) (*EvaluateSegmentResponse, error)
	// PreviewSegment previews segment results without saving
	PreviewSegment(context.Context, *PreviewSegmentRequest) (*PreviewSegmentResponse, error)
	// GetSegmentUserCount returns the count of users in a segment
	GetSegmentUserCount(context.Context, *GetSegmentUserCountRequest) (*GetSegmentUserCountResponse, error)
	// UploadStaticSegment creates a static segment from uploaded user IDs
	UploadStaticSegment(context.Context, *UploadStaticSegmentRequest) (*UploadStaticSegmentResponse, error)
	// AddUsersToStaticSegment adds users to an existing static segment
	AddUsersToStaticSegment(context.Context, *AddUsersToStaticSegmentRequest) (*AddUsersToStaticSegmentResponse, error)
	// RemoveUsersFromStaticSegment removes users from a static segment
	RemoveUsersFromStaticSegment(context.Context, *RemoveUsersFromStaticSegmentRequest) (*RemoveUsersFromStaticSegmentResponse, error)
	mustEmbedUnimplementedSegmentServiceServer()
}

// UnimplementedSegmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSegmentServiceServer struct {
}

func (UnimplementedSegmentServiceServer) CreateSegment(context.Context, *CreateSegmentRequest) (*CreateSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSegment not implemented")
}
func (UnimplementedSegmentServiceServer) UpdateSegment(context.Context, *UpdateSegmentRequest) (*UpdateSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSegment not implemented")
}
func (UnimplementedSegmentServiceServer) GetSegment(context.Context, *GetSegmentRequest) (*GetSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSegment not implemented")
}
func (UnimplementedSegmentServiceServer) ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSegments not implemented")
}
func (UnimplementedSegmentServiceServer) DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSegment not implemented")
}
func (UnimplementedSegmentServiceServer) EvaluateSegment(context.Context, *EvaluateSegmentRequest) (*EvaluateSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateSegment not implemented")
}
func (UnimplementedSegmentServiceServer) PreviewSegment(context.Context, *PreviewSegmentRequest) (*PreviewSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewSegment not implemented")
}
func (UnimplementedSegmentServiceServer) GetSegmentUserCount(context.Context, *GetSegmentUserCountRequest) (*GetSegmentUserCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSegmentUserCount not implemented")
}
func (UnimplementedSegmentServiceServer) UploadStaticSegment(context.Context, *UploadStaticSegmentRequest) (*UploadStaticSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadStaticSegment not implemented")
}
func (UnimplementedSegmentServiceServer) AddUsersToStaticSegment(context.Context, *AddUsersToStaticSegmentRequest) (*AddUsersToStaticSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUsersToStaticSegment not implemented")
}
func (UnimplementedSegmentServiceServer) RemoveUsersFromStaticSegment(context.Context, *RemoveUsersFromStaticSegmentRequest) (*RemoveUsersFromStaticSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUsersFromStaticSegment not implemented")
}
func (UnimplementedSegmentServiceServer) mustEmbedUnimplementedSegmentServiceServer() {}

// UnsafeSegmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentServiceServer will
// result in compilation errors.
type UnsafeSegmentServiceServer interface {
	mustEmbedUnimplementedSegmentServiceServer()
}

func RegisterSegmentServiceServer(s grpc.ServiceRegistrar, srv SegmentServiceServer) {
	s.RegisterService(&SegmentService_ServiceDesc, srv)
}

func _SegmentService_CreateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).CreateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_CreateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).CreateSegment(ctx, req.(*CreateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_UpdateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).UpdateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_UpdateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).UpdateSegment(ctx, req.(*UpdateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_GetSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).GetSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_GetSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).GetSegment(ctx, req.(*GetSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_ListSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).ListSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_ListSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).ListSegments(ctx, req.(*ListSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_DeleteSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).DeleteSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_DeleteSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).DeleteSegment(ctx, req.(*DeleteSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_EvaluateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).EvaluateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_EvaluateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).EvaluateSegment(ctx, req.(*EvaluateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_PreviewSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).PreviewSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_PreviewSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).PreviewSegment(ctx, req.(*PreviewSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_GetSegmentUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentUserCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).GetSegmentUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_GetSegmentUserCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).GetSegmentUserCount(ctx, req.(*GetSegmentUserCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_UploadStaticSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadStaticSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).UploadStaticSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_UploadStaticSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).UploadStaticSegment(ctx, req.(*UploadStaticSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_AddUsersToStaticSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUsersToStaticSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).AddUsersToStaticSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_AddUsersToStaticSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).AddUsersToStaticSegment(ctx, req.(*AddUsersToStaticSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_RemoveUsersFromStaticSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUsersFromStaticSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).RemoveUsersFromStaticSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_RemoveUsersFromStaticSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).RemoveUsersFromStaticSegment(ctx, req.(*RemoveUsersFromStaticSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SegmentService_ServiceDesc is the grpc.ServiceDesc for SegmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SegmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.segment.v1.SegmentService",
	HandlerType: (*SegmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSegment",
			Handler:    _SegmentService_CreateSegment_Handler,
		},
		{
			MethodName: "UpdateSegment",
			Handler:    _SegmentService_UpdateSegment_Handler,
		},
		{
			MethodName: "GetSegment",
			Handler:    _SegmentService_GetSegment_Handler,
		},
		{
			MethodName: "ListSegments",
			Handler:    _SegmentService_ListSegments_Handler,
		},
		{
			MethodName: "DeleteSegment",
			Handler:    _SegmentService_DeleteSegment_Handler,
		},
		{
			MethodName: "EvaluateSegment",
			Handler:    _SegmentService_EvaluateSegment_Handler,
		},
		{
			MethodName: "PreviewSegment",
			Handler:    _SegmentService_PreviewSegment_Handler,
		},
		{
			MethodName: "GetSegmentUserCount",
			Handler:    _SegmentService_GetSegmentUserCount_Handler,
		},
		{
			MethodName: "UploadStaticSegment",
			Handler:    _SegmentService_UploadStaticSegment_Handler,
		},
		{
			MethodName: "AddUsersToStaticSegment",
			Handler:    _SegmentService_AddUsersToStaticSegment_Handler,
		},
		{
			MethodName: "RemoveUsersFromStaticSegment",
			Handler:    _SegmentService_RemoveUsersFromStaticSegment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "segment/v1/segment.proto",
}
